### ISSUE TITLE
Грамматическая ошибка

### ISSUE THREAD

**Issue by B1loliddin** [p0dyakov/p0dyakov#1]
Здравствуйте Захар. Вы неправильно написали слово **Unsplash**, написали **Unplash**, в ряду с ссылками указанные на ваши профили.

<img width="840" alt="Screenshot 2024-08-14 at 15 05 37" src="https://github.com/user-attachments/assets/d06951ce-5ea6-4677-a79f-c334a53296e4">

**Comment by p0dyakov** [comment]
Спасибо!

**Comment by B1loliddin** [comment]
Пожалуйста.
